#! /bin/sh
PATH=/sbin:/usr/sbin:/bin:/usr/bin:$HOME/bin
DESC="the background process for"
NAME=megaprompt
DAEMON=$HOME/.cargo/bin/megaprompt
DAEMON_ARGS="--daemon"
PIDFILE=$HOME/.run/$NAME.pid
LOG=$HOME/.run/$NAME
SCRIPTNAME=$HOME/bin/megapromptd

CMD="start-stop-daemon --quiet --pidfile $PIDFILE"

[ -x "$DAEMON" ] || exit 0

[ -r /etc/default/$NAME ] && . /etc/default/$NAME

. /lib/init/vars.sh

VERBOSE=yes

. /lib/lsb/init-functions

do_start()
{
  $CMD --start --exec $DAEMON --test > /dev/null || return 1
  $CMD --background --start --make-pidfile --exec $DAEMON -- $DAEMON_ARGS || return 2
}

do_stop()
{
  $CMD --stop --retry=TERM/30/KILL/5 --name $NAME
  RETVAL="$?"
  [ "$RETVAL" = 2 ] && return 2
  $CMD --stop --oknodo --retry=0/30/KILL/5 --exec $DAEMON
  [ "$?" = 2 ] && return 2
  rm -f $PIDFILE
  return "$RETVAL"
}

do_reload() {
  $CMD --stop --signal 1 --pidfile $PIDFILE --name $NAME
  return 0
}

case "$1" in
start)
  [ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
  do_start
  case "$?" in
    0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
    2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
  esac
  ;;

stop)
  [ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
  do_stop
  case "$?" in
    0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
    2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
  esac
  ;;

status)
  status_of_proc -p "$PIDFILE" "megapromptd" "$NAME" && exit 0 || exit $?
  ;;

restart|force-reload)
  log_daemon_msg "Restarting $DESC" "$NAME"
  do_stop
  case "$?" in
    0|1)
      do_start
      case "$?" in
        0) log_end_msg 0 ;;
        1) log_end_msg 1 ;; # Old process is still running
        *) log_end_msg 1 ;; # Failed to start
      esac
      ;;
    *)
      log_end_msg 1
      ;;
  esac
  ;;
*)
  echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
  exit 3
  ;;
esac
